# Generated by Django 4.1.2 on 2022-10-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='order',
        ),
    ]
